export const publishers = [
  { value: "global_times", label: "Global Times" },
  { value: "pulse_chronicle", label: "Pulse Chronicle" },
  { value: "daily_insight", label: "Daily Insight" },
  { value: "prime_bulletin", label: "Prime Bulletin" },
  { value: "news_sphere", label: "NewsSphere" },
  { value: "tech_edge_news", label: "TechEdge News" },
  { value: "innovation_digest", label: "Innovation Digest" },
  { value: "digital_pulse", label: "Digital Pulse" },
  { value: "sports_weekly", label: "Sports Weekly" },
  { value: "victory_times", label: "Victory Times" },
  { value: "capital_watch", label: "Capital Watch" },
  { value: "profit_horizon", label: "Profit Horizon" },
  { value: "lifestyle_insider", label: "Lifestyle Insider" },
  { value: "pop_culture_now", label: "PopCulture Now" },
  { value: "wanderlust_daily", label: "Wanderlust Daily" },
  { value: "vitality_times", label: "Vitality Times" },
  { value: "green_earth_news", label: "GreenEarth News" },
  { value: "metro_chronicle", label: "Metro Chronicle" },
  { value: "science_quest", label: "Science Quest" },
  { value: "explorers_post", label: "Explorer’s Post" },
];
