export const Tags = [
  { value: "world", label: "World" },
  { value: "technology", label: "Technology" },
  { value: "sports", label: "Sports" },
  { value: "health", label: "Health" },
  { value: "finance", label: "Finance" },
  { value: "politics", label: "Politics" },
  { value: "entertainment", label: "Entertainment" },
  { value: "lifestyle", label: "Lifestyle" },
  { value: "science", label: "Science" },
  { value: "education", label: "Education" },
  { value: "travel", label: "Travel" },
  { value: "culture", label: "Culture" },
  { value: "opinion", label: "Opinion" },
  { value: "business", label: "Business" },
  { value: "environment", label: "Environment" },
  { value: "history", label: "History" },
  { value: "technology", label: "Tech" },
  { value: "food", label: "Food" },
];
